---
- name: Copy for linux
  hosts: webservers
  tasks:
   - name: Copy your file to the webservers
     ansible.builtin.copy:
       src: /home/ec2-user/testfile
       dest: /home/ec2-user/testfile
       mode: u+rw,g-wx,o-rwx

- name: Copy for ubuntu
  hosts: ubuntuservers
  tasks:
   - name: Copy your file to the ubuntuservers
     ansible.builtin.copy:
       src: /home/ec2-user/testfile
       dest: /home/ubuntu/testfile
       mode: u+rw,g-wx,o-rwx

- name: Copy for node1
  hosts: node1
  tasks:
   - name: Copy using inline content
     ansible.builtin.copy:
       content: 'This is content of file_3'
       dest: /home/ec2-user/testfile_3

   - name: Create a new text file
     ansible.builtin.shell: "echo Hello World > /home/ec2-user/testfile_4"