- name: create a user
  hosts: all
  become: true
  vars_files:
    - secret.yaml
  tasks:
    - name: creating user
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ password | password_hash ('sha512') }}"