---
- name: create a user using a variable
  hosts: centos
  become: true
  vars:
    user: lisa
    ansible_ssh_private_key_file: "/home/ec2-user/first-key-pair.pem"
  tasks:
    - name: create a user {{ user }}
      ansible.builtin.user:
        name: "{{ user }}"

- name: create a user using a variable
  hosts: debian
  become: true
  vars:
    user: lisa
    ansible_user: ubuntu
    ansible_ssh_private_key_file: "/home/ec2-user/first-key-pair.pem"
  tasks:
    - name: create a user {{ user }}
      ansible.builtin.user:
        name: "{{ user }}"