---
- name: db_server facts
  hosts: db_server
  tasks:
    - name: getting db_server facts
      ansible.builtin.debug:
        var: hostvars['db_server']['ansible_facts']['default_ipv4']['address']
  # To later utilize the information from the database server, we created a play from 'db_server' host to enable Ansible to gather facts from it

- name: web server configuration
  hosts: web_server
  tasks:
    - name: set hostname
      ansible.builtin.shell: "sudo hostnamectl set-hostname {{ hostname }}"

    - name: Installing python for python app
      become: yes
      ansible.builtin.package:
        name:
          - python3
          - python3-pip
        state: present
        update_cache: yes

    - name: copy the app file to the web server
      ansible.builtin.copy:
        src: /home/ubuntu/ansible-lesson/phonebook/phonebook-app.py
        dest: /home/ubuntu/

    - name: Insert private IP of database server to app file
      ansible.builtin.replace:
         path: /home/ubuntu/phonebook-app.py
         regexp: '<private_ip of db_server>'
         replace: "{{ hostvars['db_server']['ansible_facts']['default_ipv4']['address'] }}"
         backup: yes    
    # 'db_server' fact can be used here as a play from it is defined up above

    - name: copy the requirements file to the web server
      ansible.builtin.copy:
        src: /home/ubuntu/ansible-lesson/phonebook/requirements.txt
        dest: /home/ubuntu/

    - name: copy the templates folder to the web server
      ansible.builtin.copy:
        src: /home/ubuntu/ansible-lesson/phonebook/templates
        dest: /home/ubuntu/

    - name: install dependencies from requirements file
      become: yes
      ansible.builtin.pip:
        requirements: /home/ubuntu/requirements.txt

    - name: run the app
      become: yes
      ansible.builtin.shell: "nohup python3 phonebook-app.py &"
    # keeps the process in the background running with "nohup &"